In [1]:
import numpy as np

In [2]:
X = np.arange(50000000)
X

array([       0,        1,        2, ..., 49999997, 49999998, 49999999])

In [3]:
np.min(X)

0

In [4]:
np.max(X)

49999999

In [5]:
%time min(X)

CPU times: total: 1.61 s
Wall time: 1.62 s


0

In [6]:
%time np.min(X)

CPU times: total: 0 ns
Wall time: 9 ms


0

In [7]:
Y = X.reshape(5,-1)
Y

array([[       0,        1,        2, ...,  9999997,  9999998,  9999999],
       [10000000, 10000001, 10000002, ..., 19999997, 19999998, 19999999],
       [20000000, 20000001, 20000002, ..., 29999997, 29999998, 29999999],
       [30000000, 30000001, 30000002, ..., 39999997, 39999998, 39999999],
       [40000000, 40000001, 40000002, ..., 49999997, 49999998, 49999999]])

In [8]:
np.min(Y,axis=0)

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [9]:
np.min(Y,axis=1)

array([       0, 10000000, 20000000, 30000000, 40000000])

In [11]:
X = np.linspace(1,20,20).reshape(4,5)

In [12]:
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [13]:
np.sum(X)

210.0

In [14]:
np.sum(X,axis=0)

array([34., 38., 42., 46., 50.])

In [15]:
np.sum(X,axis=1)

array([15., 40., 65., 90.])

In [16]:
#求均值
np.mean(X)

10.5

In [17]:
#求中位数
np.median(X)

10.5

In [18]:
#标准差
np.std(X)

5.766281297335398

In [19]:
#方差
np.var(X)

33.25

In [20]:
#创建一组 均值为0 标准差为10 10w个数组
Z= np.random.normal(0,10,100000)
np.mean(Z),np.std(Z)

(0.019744964632789807, 10.03432637180334)

In [21]:
#ptp 表述 数组中的最大值和最小值的差
np.ptp(X)

19.0

In [22]:
q = np.linspace(0,100,5)

In [23]:
#求百分位数 
q,np.percentile(X,q)

(array([  0.,  25.,  50.,  75., 100.]),
 array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]))

In [24]:
#求累加（按行统计）
np.cumsum(X,axis=1)

array([[ 1.,  3.,  6., 10., 15.],
       [ 6., 13., 21., 30., 40.],
       [11., 23., 36., 50., 65.],
       [16., 33., 51., 70., 90.]])

In [25]:
#计算相邻向量之间的差
np.diff(X,axis=1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
#按列相乘
np.prod(X,axis= 1)

array([1.20000e+02, 3.02400e+04, 3.60360e+05, 1.86048e+06])