In [3]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim

1

In [5]:
A.ndim

2

In [6]:
a.shape

(6,)

In [7]:
A.shape

(2, 3)

In [8]:
A.size

6

In [9]:
a.dtype

dtype('int32')

In [10]:
A.dtype

dtype('int32')

#Test

In [5]:
np.ones(8)
# np 生产出来的是浮点型

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(8).dtype

dtype('float64')

In [6]:
np.ones(8,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [7]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones_like(A)
#根据最上面的 自己创建的A数组  A A = np.array([
#     [1,2,3],
#     [4,5,6]
# ])

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

#full

In [16]:
np.full(8,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [17]:
np.full((2,4),666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

In [18]:
np.full_like(A,666)

array([[666, 666, 666],
       [666, 666, 666]])

#empty

In [19]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.empty_like(A)

array([[-1133177680,         569,           0],
       [          0,           1, -2147483648]])

#arange

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#linspace #等差数组

In [25]:
#等差数组

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

##randpm模块

In [27]:
np.random.random()

0.4883238828317522

In [28]:
np.random.random(5)

array([0.27269542, 0.98997468, 0.07706312, 0.87085444, 0.56468672])

In [29]:
np.random.random((2,4))

array([[0.12655214, 0.6774784 , 0.10495708, 0.8092084 ],
       [0.94662748, 0.5386948 , 0.1058087 , 0.79549747]])

#rand

In [31]:
np.random.rand()

0.27541148810904315

In [32]:
np.random.rand(5)

array([0.41606539, 0.3073535 , 0.19418563, 0.48105168, 0.85448371])

In [33]:
np.random.rand(2,3)

array([[0.42468676, 0.99369491, 0.66006318],
       [0.48393798, 0.53741756, 0.15304838]])

In [34]:
np.random.rand(2,3,4)

array([[[0.00443706, 0.40895718, 0.39098715, 0.40957717],
        [0.40643308, 0.55035355, 0.16717997, 0.01132442],
        [0.06995305, 0.39295499, 0.94652405, 0.68831174]],

       [[0.80556187, 0.96706189, 0.08326621, 0.07013722],
        [0.1228874 , 0.10685509, 0.95257453, 0.90619816],
        [0.85949739, 0.42879781, 0.94247647, 0.22153223]]])

#randInt

In [36]:
np.random.randint(5)

3

In [37]:
np.random.randint(5,10)

9

In [4]:
np.random.randint(5,10,size=(2,4))

array([[7, 9, 5, 9],
       [5, 6, 6, 8]])

#seed

In [6]:
np.random.seed(666)
np.random.randint(5,10,size=(2,4))

array([[9, 7, 6, 9],
       [8, 8, 9, 9]])

#randn

In [8]:
np.random.randn(5)

array([ 0.01902826, -0.94376106,  0.64057315, -0.78644317,  0.60886999])

In [9]:
np.random.randn(2,4)

array([[-0.93101185,  0.97822225, -0.73691806, -0.29873262],
       [-0.46058737, -1.08879299, -0.57577075, -1.68290077]])

#normal

In [10]:
np.random.normal()

0.2291852477040214

In [11]:
np.random.normal(10,1000,20)

array([-1746.62522343,   854.63261866,   287.21986341,   862.90153297,
         204.59960304,  1320.63771572,  1553.84360007,  -519.04802429,
        -646.47229734,  -191.5057011 ,  -690.61583283,   697.13795436,
         -16.07575641,  -819.75831975,   306.5537839 ,  -302.67950363,
        -601.30127441,  -811.75150479,   907.12270311,   146.0786118 ])

In [12]:
np.random.normal(10,100,size=(4,6))

array([[ -15.86548011,  121.07656409,   -8.84243873,    5.85107071,
         -88.47919123, -125.22817585],
       [  29.43238455,   36.72393512,  -32.64736981,  154.77350574,
          -9.63061002,  161.814514  ],
       [  17.72218828,    3.60086759,  104.59234072,  130.40910055,
         -35.12407353, -148.74465098],
       [-176.88554809,   20.03773732, -299.48705895,  349.35167821,
          -2.66687787,  -83.71302591]])

#uniform  左开右闭

In [13]:
np.random.uniform()

0.9691891684335366

In [14]:
np.random.uniform(1,5)

3.9538844862833527

In [17]:
np.random.uniform?

Docstring:
uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

.. note::
    New code should use the `~numpy.random.Generator.uniform`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than or equal to high.  The high limit may be included in the 
    returned array of floats due to floating-point rounding in the 
    equation ``low + (high-low) * random_sample()``.  The default v