#基础索引

In [2]:
import numpy as np

In [3]:
#一堆数组 也看做向量
#一般用小写字母表示
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#二维数组 看做是：矩阵
#一般用 大写字母表示
A = np.arange(20).reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#一维数组

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[0]

0

In [6]:
a[4]

4

In [7]:
a[-1]

9

In [8]:
a[0:5]

array([0, 1, 2, 3, 4])

In [9]:
a[:5]

array([0, 1, 2, 3, 4])

In [10]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [11]:
a[-3:]

array([7, 8, 9])

In [12]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[::2]

array([0, 2, 4, 6, 8])

二维数组

In [16]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A[0,0]

0

In [18]:
A[0,:]

array([0, 1, 2, 3, 4])

In [19]:
A[0]

array([0, 1, 2, 3, 4])

In [20]:
A[-1]

array([15, 16, 17, 18, 19])

In [21]:
A[:0]

array([], shape=(0, 5), dtype=int32)

In [22]:
A[:,0]

array([ 0,  5, 10, 15])

In [23]:
A[:,-1]

array([ 4,  9, 14, 19])

In [24]:
A[:2,:4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [25]:
A[::-1,::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [26]:
X = A[:2,:3]

In [27]:
X

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X[0,0] = 666

In [29]:
X

array([[666,   1,   2],
       [  5,   6,   7]])

In [30]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [31]:
A

array([[666,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [32]:
A[0,0] = 0
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
X

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])