In [1]:
import numpy as np

#最大值 最小值

In [4]:
#随机生成数字
x =np.random.normal(0,1,size=1000000)
x

array([ 0.43696391, -2.24506272, -0.41854572, ...,  1.7061973 ,
        0.08751757,  1.29562688])

In [7]:
#获取随机数字 数组中的最小值
np.min(x)

-4.730570549475327

In [5]:
#获取最小值 所在索引
np.argmin(x)

423042

In [6]:
x[np.argmin(x)]

-4.730570549475327

In [9]:
np.max(x)

4.582264379748383

In [10]:
x[np.argmax(x)]

4.582264379748383

#排序

In [13]:
x=  np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.shuffle(x)
x

array([9, 1, 3, 4, 6, 2, 0, 5, 8, 7])

In [15]:
x.sort()

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#使用索引

In [21]:
np.random.shuffle(x)
x

array([2, 4, 9, 3, 1, 8, 5, 7, 0, 6])

In [22]:
#排序，但是把之前的索引 进行排序
np.argsort(x)

array([8, 4, 0, 3, 1, 6, 9, 7, 5, 2], dtype=int64)

#分区

In [23]:
#以5为界 左右分开
np.partition(x,5)

array([0, 1, 2, 4, 3, 5, 8, 7, 9, 6])

In [24]:
#以5为界 左右分开 显示的索引
np.argpartition(x,5)

array([8, 4, 0, 1, 3, 6, 5, 7, 2, 9], dtype=int64)

#高维情况

In [25]:
X= np.random.randint(10,size=(5,5))
X

array([[0, 3, 5, 9, 5],
       [4, 8, 9, 3, 2],
       [2, 5, 6, 7, 0],
       [8, 6, 5, 1, 5],
       [7, 7, 8, 9, 2]])

In [26]:
np.sort(X)

array([[0, 3, 5, 5, 9],
       [2, 3, 4, 8, 9],
       [0, 2, 5, 6, 7],
       [1, 5, 5, 6, 8],
       [2, 7, 7, 8, 9]])

In [27]:
np.argsort(X,axis=1)

array([[0, 1, 2, 4, 3],
       [4, 3, 0, 1, 2],
       [4, 0, 1, 2, 3],
       [3, 2, 4, 1, 0],
       [4, 0, 1, 2, 3]], dtype=int64)

In [28]:
np.partition(X,2,axis=1)

array([[0, 3, 5, 9, 5],
       [2, 3, 4, 8, 9],
       [0, 2, 5, 7, 6],
       [1, 5, 5, 8, 6],
       [2, 7, 7, 9, 8]])