In [3]:
import numpy as np

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [8]:
x[2:8:2]

array([2, 4, 6])

In [9]:
[x[2],x[5],x[8]]

[2, 5, 8]

In [10]:
index = [2,5,8]
x[index]

array([2, 5, 8])

In [12]:
index = np.array([[1,3,5],[2,4,6]])
x[index]

array([[1, 3, 5],
       [2, 4, 6]])

#索引 用于 二维数组

In [17]:
X = x.reshape(2,-1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
#X[row,col] =>  
#X[0,0] =>X[0] 
#X[1,2]=>第二行第三列=>X[7]
#X[0,4]=>X[4]

row = np.array([0,1,0])
col = np.array([0,2,4])
X[row,col]

array([0, 7, 4])

In [19]:
X[0,col]

array([0, 2, 4])

In [20]:
X[row,:2]

array([[0, 1],
       [5, 6],
       [0, 1]])

In [21]:
col =[True,False,True,False,True]
X[0,col]

array([0, 2, 4])

#比较

In [22]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [24]:
x >=2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [25]:
x ==3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [26]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [27]:
x * x ==9

array([False, False, False,  True, False, False, False, False, False,
       False])

In [28]:
 X>1

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

#比较结果和 索引的使用

In [29]:
x[x>3]

array([4, 5, 6, 7, 8, 9])

In [30]:
x[x%2 == 0]

array([0, 2, 4, 6, 8])

#比较的更多应用

In [31]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#对 数组中非0的项目
np.count_nonzero(x<5)

5

In [33]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
np.sum(x<5)

5

In [35]:
np.any(x<0)

False

In [36]:
np.any(x>5)

True

In [37]:
np.all(x>9)

False

In [38]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])