# 1. 加载数据集

In [1]:
import numpy as np

#datasets sklearn 给我们的数据集
from sklearn import datasets

In [4]:
#加载鸢尾花 数据集
iris = datasets.load_iris()

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [21]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris.data.shape

(150, 4)

In [8]:
#数据集 分类的名称
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
#数据集 数据集字段
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
#数据集分类类别 
y= iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#2.拆分数据集 

In [11]:
#根据 数据集分类类别 长度 打乱
shuffle_index = np.random.permutation(len(y))
shuffle_index

array([ 87,  52,  92, 117, 146, 129,  60, 130,  21,  42,  72, 147,  57,
         3,  81,  46,  30,  34, 105,  69, 137,  45,  39,  95,  16,  12,
       140, 138,  65,   8,  84,  53,  91,  67,  74,  11, 132,  56,  63,
       104, 122,  83,  85,   1,   0,  24, 134, 142,  66, 136,  96,   4,
        44, 131, 119, 135,  28, 116,  32,  98, 113,  75,  20, 120,  36,
        50,  19, 145, 100,   2,  31,  37,  97, 114, 115,  40, 102, 133,
         5, 141,  54, 112, 139,  18, 126, 108,  51,   6,  29,  90,  79,
       149,  22, 101,   9,  77, 143,  93,  47,  17,  73,  55,  70, 111,
       106,  76,  10,   7, 125,  82, 148,  58,  61,  14,  25,  86,  64,
       110,  15, 123,  49, 107,  59,  33,  41, 109, 121,  88,  62,  99,
        94, 103,  27,  68,  48,  71, 118,  80,  23,  13,  78, 127, 124,
        35,  89,  38,  26, 128,  43, 144])

In [17]:
train_ratio =0.8

In [18]:
train_size = int(len(y)*train_ratio)
train_size

120

In [19]:
train_index = shuffle_index[0:train_size]
test_index = shuffle_index[train_size:len(shuffle_index)]

In [22]:
#将 数据与类别  分为 训练和测试

X_train = X[train_index]
y_train = y[train_index]

X_test = X[test_index]
y_test = y[test_index]

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用sklearn 进行 分类

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=666)

In [27]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [28]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 3.预测

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
#使用knn 算法   k = 5
knn_classifier  =  KNeighborsClassifier(n_neighbors=5)

In [31]:
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [33]:
y_predict = knn_classifier.predict(X_test)
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

## 4. 评价预测结果

In [34]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [35]:
#比较 预测的类别 与 正确的 数据了类别 进行 比对
np.sum(y_predict == y_test)

30

In [36]:
#正确率
accuracy = np.sum(y_predict == y_test) / len(y_test)
accuracy

1.0

#使用sklearn 进行计算正确率

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test,y_predict)

1.0

#直接使用 knn里面的score方法进行 正确率的计算

In [39]:
knn_classifier.score(X_test,y_test)

1.0